version: '3'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_HOST: 'localhost'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./tmp/db:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    #command: bash -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - .env
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db