export const FETCH_GEOCODER_DATA = 'FETCH_GEOCODER_DATA';
export const FETCH_GEOCODER_DATA_FAIL = 'FETCH_GEOCODER_DATA_FAIL';
export const FETCH_GEOCODER_DATA_SUCCESS = 'FETCH_GEOCODER_DATA_SUCCESS';
export const DELETE_GEOCODER_DATA = 'DELETE_GEOCODER_DATA';
export const EDIT_GEOCODER_DATA = 'EDIT_GEOCODER_DATA';
export const EDIT_GEOCODER_DATA_SUCCESS = 'EDIT_GEOCODER_DATA_SUCCESS';
export const LOAD_GEOCODER_DATA = 'LOAD_GEOCODER_DATA';
